/* はちみつ砲 簡易版ガイド（決定木）データ。honeycup_simple.json をそのまま埋め込み。
   既存のPattern DB / valid判定 / 通し練習とは独立した「簡易版ガイドモード」専用。
   出典: https://shiwehi.com/tetris/template/honeycup.php
   mapping_status は CONFIRMED（node↔canvas対応・条件はユーザー確認済み）。 */
window.TT_HC_SIMPLE = {
  "name": "honeycup_simple",
  "title": "はちみつ砲の派生（簡単ver.）決定木",
  "source": "https://shiwehi.com/tetris/template/honeycup.php",
  "description": "はちみつ砲の派生フローチャート(簡単ver.)を決定木化。各nodeは盤面(fumen v115 / 10x可変)。edgesはネクスト・ホールドの順序などの分岐条件。",
  "mapping_status": "CONFIRMED: node↔canvas対応はユーザー確認済み（簡単ver画像→honeycup #0-35）。",
  "legend": {
    "_about": "条件はネクスト＋ホールドを合わせた『使用可能順(queue)』での前後で判定する。idx(P)=ミノPを使える早さ(小さいほど早い)。",
    "O>J": { "meaning": "OがJより先（ネクスト＋ホールドでOを先に使える）", "eval": "idx('O') < idx('J')" },
    "J>O": { "meaning": "JがOより先", "eval": "idx('J') < idx('O')" },
    "S>L": { "meaning": "SがLより先", "eval": "idx('S') < idx('L')" },
    "L>S": { "meaning": "LがSより先", "eval": "idx('L') < idx('S')" },
    "T早め": { "meaning": "Tが早く来る", "eval": "idx('T') が小さい（目安: S/Lの組み完了より前にTが使える）" },
    "T遅め": { "meaning": "Tが遅く来る", "eval": "idx('T') が大きい（上記の否定）" },
    "確定": { "meaning": "分岐なし（一意に決まる）", "eval": "true（無条件）" },
    "LZ早い方で屋根を付ける": { "meaning": "LとZの早い方で屋根(フタ)を付ける", "eval": "roof = (idx('L') < idx('Z') ? 'L' : 'Z')" },
    "パフェ": { "meaning": "うまくいけばパーフェクトクリア（結果・分岐条件ではない）", "eval": null }
  },
  "start": "root",
  "nodes": [
    { "id": "root", "label": "1巡目の土台（O・Jを置く前）", "type": "board", "canvas": 0,
      "fumen": "v115@8gg0AeR4Feg0R4glDewwh0ilAeBtxwRpzhAeBtwwRpJeAgH",
      "grid": ["..........", "..........", "..........", ".........J", ".SS......J", "SSL....TJJ", "LLL.ZZTTOO", "IIII.ZZTOO"],
      "edges": [{ "condition": "O>J", "to": "A" }, { "condition": "O>J", "to": "B" }, { "condition": "J>O", "to": "C" }] },
    { "id": "A", "label": "O>J かつ S>L の組み（2巡目TSTセット）", "type": "board", "canvas": 5,
      "fumen": "v115@fgzhFexwR4Beh0BewwR4Ceg0ilwwB8AeBtg0glRpC8BeBtA8RpC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "TTSS..JJ..", "TSS...JLLL", "TGG.ZZJLOO", "GGG..ZZGOO", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "T早め", "to": "A1" }, { "condition": "T早め(別形)", "to": "A2" }] },
    { "id": "B", "label": "O>J かつ L>S の組み", "type": "board", "canvas": 6,
      "fumen": "v115@fgzhFexwR4Beglg0BewwR4Cegli0wwB8AeBthlRpC8BeBtA8RpC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "TTSS..LJ..", "TSS...LJJJ", "TGG.ZZLLOO", "GGG..ZZGOO", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "T遅め", "to": "B1" }, { "condition": "T遅め(別形)", "to": "B2" }] },
    { "id": "A1", "label": "O>J,S>L,T早め → 結果1", "type": "board", "canvas": 7,
      "fumen": "v115@fgzhFeh0R4BeRpBeg0R4CeRpglwwg0B8AeBtilwwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "JJSS..OO..", "JSS...OOLT", "JGG.ZZLLLT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "A2", "label": "O>J,S>L,T早め → 結果2（など）", "type": "board", "canvas": 8,
      "fumen": "v115@fgwhilFewhglR4Beh0BewhR4Ceg0RpwwwhB8AeBtg0RpwwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "ILLL......", "ILSS..JJ..", "ISS...JOOT", "IGG.ZZJOOT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "B1", "label": "O>J,L>S,T遅め → 結果1", "type": "board", "canvas": 9,
      "fumen": "v115@fgwhi0FewhRpg0BeglQ4BewhRpCeglR4wwwhB8AeBthlQ4wwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IJJJ......", "IOOJ..LS..", "IOO...LSST", "IGG.ZZLLST", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "B2", "label": "O>J,L>S,T遅め → 結果2（など）", "type": "board", "canvas": 1,
      "fumen": "v115@fgzhFeh0R4BeRpBeg0R4CeRpglA8g0B8wwBtilD8xwBtF8wwJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "JJSS..OO..", "JSS...OOLG", "JGGTZZLLLG", "GGGTTZZGGG", "GGGTGGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "C", "label": "J>O の組み", "type": "board", "canvas": 3,
      "fumen": "v115@+gR4GeR4glDewwBeilAeBtxwRpzhAeBtwwRpJeAgH",
      "grid": ["..........", "..........", ".SS.......", "SSL....T..", "LLL.ZZTTOO", "IIII.ZZTOO"],
      "edges": [{ "condition": "S>L", "to": "D" }, { "condition": "確定", "to": "E" }] },
    { "id": "D", "label": "J>O かつ S>L", "type": "board", "canvas": 30,
      "fumen": "v115@dgRpwhGeRpwhAeR4BeglAeh0whR4CeglAeg0wwwhB8AeBthlg0wwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["........OO", "I.......OO", "I.SS..L.JJ", "ISS...L.JT", "IGG.ZZLLJT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "LZ早い方で屋根を付ける", "to": "D1" }] },
    { "id": "D1", "label": "J>O,S>L → 屋根付け後", "type": "board", "canvas": 31,
      "fumen": "v115@dgRpwhGeRpwhAeR4BeglAeh0whR4CeglAeg0wwwhB8wwjlg0wwC8xwhlA8xwC8wwJ8AeE8JeAgH",
      "grid": ["........OO", "I.......OO", "I.SS..L.JJ", "ISS...L.JT", "IGGTLLLLJT", "GGGTTLLGTT", "GGGTGGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "E", "label": "J>O かつ 確定", "type": "board", "canvas": 2,
      "fumen": "v115@zgzhili0D8glR4Btg0D8R4B8BtC8ywH8wwE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGLSSZZJ", "GGGGSSGGZZ", "GGGTTTGGGG", "GGGGTGGGGG"],
      "edges": [{ "condition": "(運が良いと)パフェ", "to": "E1" }, { "condition": "(運が良いと)パフェ", "to": "E2" }] },
    { "id": "E1", "label": "J>O,確定 → 結果1（運が良いとパフェ）", "type": "board", "canvas": 12,
      "fumen": "v115@zgzhili0D8glR4Btg0D8R4B8BtC8ywH8wwE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGLSSZZJ", "GGGGSSGGZZ", "GGGTTTGGGG", "GGGGTGGGGG"],
      "edges": [] },
    { "id": "E2", "label": "J>O,確定 → 結果2（運が良いとパフェ）", "type": "board", "canvas": 24,
      "fumen": "v115@zgzhili0D8ywBtg0D8R4B8BtC8R4wwH8glE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGTTTZZJ", "GGGGSSGGZZ", "GGGSSTGGGG", "GGGGLGGGGG"],
      "edges": [] }
  ],
  "conditions_confirmed_by_user": true,
  "mapping_confirmed_by_user": true,
  "usage": {
    "how_to_traverse": "start のノードから開始。現在ノードの edges を順に見て、condition を legend[condition].eval でプレイヤーのqueue(ネクスト+ホールド)に対して評価し、最初に真になった edge の to へ進む。葉(edges空)に到達したら、その node.fumen が推奨盤面。",
    "idx_definition": "idx(P)=ミノPを最短で使える順番(0始まり,小さいほど早い)。ホールド中のミノは即使用可とみなしqueue先頭側に含める。",
    "board_fields": "各nodeの fumen(=v115@..., fumen.zui.jpで開ける) または grid(10列の文字盤面: . 空 / IOTSZJL ミノ / G 確定スタック) を描画に使う。"
  }
};
