/* はちみつ砲 簡易版ガイド（決定木）データ。honeycup_simple.json をそのまま埋め込み。
   既存のPattern DB / valid判定 / 通し練習とは独立した「簡易版ガイドモード」専用。
   出典: https://shiwehi.com/tetris/template/honeycup.php （mapping_status は DRAFT：目安として使用）。 */
window.TT_HC_SIMPLE = {
  "name": "honeycup_simple",
  "title": "はちみつ砲の派生（簡単ver.）決定木",
  "source": "https://shiwehi.com/tetris/template/honeycup.php",
  "description": "はちみつ砲の派生フローチャート(簡単ver.)を決定木化。各nodeは盤面(fumen v115 / 10x可変)。edgesはネクスト・ホールドの順序などの分岐条件。",
  "mapping_status": "DRAFT: 各node.canvasは簡単ver画像→honeycup 36図への目視対応。要確認・差し替え容易。",
  "legend": {
    "O>J": "OがJより先", "J>O": "JがOより先", "S>L": "SがLより先", "L>S": "LがSより先",
    "T早め": "Tが早い", "T遅め": "Tが遅い", "確定": "分岐なし(一意)",
    "LZ早い方で屋根を付ける": "LとZの早い方で屋根(フタ)", "パフェ": "うまくいけばパーフェクトクリア"
  },
  "start": "root",
  "nodes": [
    { "id": "root", "label": "1巡目の土台（O・Jを置く前）", "type": "board", "canvas": 0,
      "fumen": "v115@8gg0AeR4Feg0R4glDewwh0ilAeBtxwRpzhAeBtwwRpJeAgH",
      "grid": ["..........", "..........", "..........", ".........J", ".SS......J", "SSL....TJJ", "LLL.ZZTTOO", "IIII.ZZTOO"],
      "edges": [{ "condition": "O>J", "to": "A" }, { "condition": "O>J", "to": "B" }, { "condition": "J>O", "to": "C" }] },
    { "id": "A", "label": "O>J かつ S>L の組み（2巡目TSTセット）", "type": "board", "canvas": 5,
      "fumen": "v115@fgzhFexwR4Beh0BewwR4Ceg0ilwwB8AeBtg0glRpC8BeBtA8RpC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "TTSS..JJ..", "TSS...JLLL", "TGG.ZZJLOO", "GGG..ZZGOO", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "T早め", "to": "A1" }, { "condition": "T早め(別形)", "to": "A2" }] },
    { "id": "B", "label": "O>J かつ L>S の組み", "type": "board", "canvas": 6,
      "fumen": "v115@fgzhFexwR4Beglg0BewwR4Cegli0wwB8AeBthlRpC8BeBtA8RpC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "TTSS..LJ..", "TSS...LJJJ", "TGG.ZZLLOO", "GGG..ZZGOO", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "T遅め", "to": "B1" }, { "condition": "T遅め(別形)", "to": "B2" }] },
    { "id": "A1", "label": "O>J,S>L,T早め → 結果1", "type": "board", "canvas": 7,
      "fumen": "v115@fgzhFeh0R4BeRpBeg0R4CeRpglwwg0B8AeBtilwwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "JJSS..OO..", "JSS...OOLT", "JGG.ZZLLLT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "A2", "label": "O>J,S>L,T早め → 結果2（など）", "type": "board", "canvas": 8,
      "fumen": "v115@fgwhilFewhglR4Beh0BewhR4Ceg0RpwwwhB8AeBtg0RpwwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "ILLL......", "ILSS..JJ..", "ISS...JOOT", "IGG.ZZJOOT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "B1", "label": "O>J,L>S,T遅め → 結果1", "type": "board", "canvas": 9,
      "fumen": "v115@fgwhi0FewhRpg0BeglQ4BewhRpCeglR4wwwhB8AeBthlQ4wwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["..........", "IJJJ......", "IOOJ..LS..", "IOO...LSST", "IGG.ZZLLST", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "B2", "label": "O>J,L>S,T遅め → 結果2（など）", "type": "board", "canvas": 1,
      "fumen": "v115@fgzhFeh0R4BeRpBeg0R4CeRpglA8g0B8wwBtilD8xwBtF8wwJ8AeE8JeAgH",
      "grid": ["..........", "IIII......", "JJSS..OO..", "JSS...OOLG", "JGGTZZLLLG", "GGGTTZZGGG", "GGGTGGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "C", "label": "J>O の組み", "type": "board", "canvas": 3,
      "fumen": "v115@+gR4GeR4glDewwBeilAeBtxwRpzhAeBtwwRpJeAgH",
      "grid": ["..........", "..........", ".SS.......", "SSL....T..", "LLL.ZZTTOO", "IIII.ZZTOO"],
      "edges": [{ "condition": "S>L", "to": "D" }, { "condition": "確定", "to": "E" }] },
    { "id": "D", "label": "J>O かつ S>L", "type": "board", "canvas": 30,
      "fumen": "v115@dgRpwhGeRpwhAeR4BeglAeh0whR4CeglAeg0wwwhB8AeBthlg0wwC8BeBtA8xwC8AeJ8AeE8JeAgH",
      "grid": ["........OO", "I.......OO", "I.SS..L.JJ", "ISS...L.JT", "IGG.ZZLLJT", "GGG..ZZGTT", "GGG.GGGGGG", "GGGG.GGGGG"],
      "edges": [{ "condition": "LZ早い方で屋根を付ける", "to": "D1" }] },
    { "id": "D1", "label": "J>O,S>L → 屋根付け後", "type": "board", "canvas": 31,
      "fumen": "v115@dgRpwhGeRpwhAeR4BeglAeh0whR4CeglAeg0wwwhB8wwjlg0wwC8xwhlA8xwC8wwJ8AeE8JeAgH",
      "grid": ["........OO", "I.......OO", "I.SS..L.JJ", "ISS...L.JT", "IGGTLLLLJT", "GGGTTLLGTT", "GGGTGGGGGG", "GGGG.GGGGG"],
      "edges": [] },
    { "id": "E", "label": "J>O かつ 確定", "type": "board", "canvas": 2,
      "fumen": "v115@zgzhili0D8glR4Btg0D8R4B8BtC8ywH8wwE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGLSSZZJ", "GGGGSSGGZZ", "GGGTTTGGGG", "GGGGTGGGGG"],
      "edges": [{ "condition": "(運が良いと)パフェ", "to": "E1" }, { "condition": "(運が良いと)パフェ", "to": "E2" }] },
    { "id": "E1", "label": "J>O,確定 → 結果1（運が良いとパフェ）", "type": "board", "canvas": 12,
      "fumen": "v115@zgzhili0D8glR4Btg0D8R4B8BtC8ywH8wwE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGLSSZZJ", "GGGGSSGGZZ", "GGGTTTGGGG", "GGGGTGGGGG"],
      "edges": [] },
    { "id": "E2", "label": "J>O,確定 → 結果2（運が良いとパフェ）", "type": "board", "canvas": 24,
      "fumen": "v115@zgzhili0D8ywBtg0D8R4B8BtC8R4wwH8glE8JeAgH",
      "grid": ["..........", "IIIILLLJJJ", "GGGGTTTZZJ", "GGGGSSGGZZ", "GGGSSTGGGG", "GGGGLGGGGG"],
      "edges": [] }
  ]
};
