// テンプレ練習データ — tetrismaps版(New/コレクション)を実fumenデコーダで復元・統合
// forms[].grid: I/L/O/Z/T/J/S=新規に置く目標ミノ / X=確定スタック(灰・土台prefill) / _=空。床接地。
// percent=成功率(無=null), pieces=使用ミノ, comment=注記。色セルは%4==0(=ちょうどNミノ)・8セル以上のみ採用・重複除去・上限80。
(function () {
  window.TT_TEMPLATES = { templates: [
    {
      id: "honeycup", title: "はちみつ砲", source: "https://w.atwiki.jp/tetrismaps/pages/248.html", total: 8,
      forms: [
        { grid: ["IIII______", "JJSS__OO__", "JSS___OOLX", "JXX_ZZLLLX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 96.87, pieces: "L, J", comment: "96.87% (L, J)" },
        { grid: ["ILLL______", "ILSS__JJ__", "ISS___JOOX", "IXX_ZZJOOX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 96.87, pieces: "S、O", comment: "96.87%（S、O）" },
        { grid: ["IJJJ______", "IOOJ__LS__", "IOO___LSSX", "IXX_ZZLLSX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 96.87, pieces: "L、O", comment: "96.87%（L、O）" },
        { grid: ["LL________", "IL________", "ILSS__JJ__", "ISS___JOOX", "IXX_ZZJOOX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 95.91, pieces: "I、O", comment: "95.91%（I、O）" },
        { grid: ["_________J", "I________J", "I_SS__OOJJ", "ISS___OOLX", "IXX_ZZLLLX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 84.33, pieces: "L", comment: "84.33%（L）" },
        { grid: ["_______S__", "_______SS_", "IIII__JJS_", "LLL___JOOX", "LXX_ZZJOOX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 84.25, pieces: "L、O→J", comment: "84.25%（L、O→J）" },
        { grid: ["________OO", "I_______OO", "I_SS__L_JJ", "ISS___L_JX", "IXX_ZZLLJX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 70.63, pieces: "J", comment: "70.63%（J）" },
        { grid: ["______I__L", "JJSS__ILLL", "JSS___IOOX", "JXX_ZZIOOX", "XXX__ZZXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: 70.04, pieces: "Z、O", comment: "70.04%（Z、O）" },
      ],
    },
    {
      id: "dtcannonopener", title: "開幕DT砲", source: "https://w.atwiki.jp/tetrismaps/pages/16.html", total: 176,
      forms: [
        { grid: ["____SS____", "___SSL____", "___LLL____"], percent: null, pieces: "", comment: "" },
        { grid: ["____SS____", "___SSL_J__", "___LLL_JJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____SS_ZZ_", "___SSL_JZZ", "___LLL_JJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____T_____", "___TTT____", "____SS_ZZ_", "___SSL_JZZ", "___LLL_JJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____T_____", "___TTT____", "____SS_ZZ_", "OO_SSL_JZZ", "OO_LLL_JJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____T_____", "___TTTI___", "____SSIZZ_", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___L______", "___LT_____", "___TTTI___", "____SSIZZ_", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___L______", "JJ_LT_____", "J__TTTI___", "J___SSIZZ_", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___LZZ____", "JJ_LTZZ___", "J__TTTI___", "J___SSIZZ_", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___LZZ____", "JJ_LTZZOO_", "J__TTTIOO_", "J___SSIZZ_", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___LZZ___I", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_____S____", "__LL_SS___", "___LZZS__I", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL____SS", "___LZZ_SSI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_______Z__", "__LL__ZZSS", "___LZZZSSI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_____SSZ__", "__LLSSZZSS", "___LZZZSSI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_____SSZ__", "__LLSSZZSS", "___LZZZSSI", "JJ_LTZZOOI", "J__TTTIOOI", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___L______", "JJ_LX_____", "J__XXXX___", "J___XXXXX_", "XX_XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "DT砲新パフェルート案" },
        { grid: ["_________Z", "__XX____ZZ", "___X__SSZI", "XX_XXSSOOI", "X__XXXXOOI", "X___XXXXXI", "XX_XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "こんな感じ OI土台" },
        { grid: ["_______SSX", "ZZXXOOSSXX", "_ZZXOOXXXX"], percent: null, pieces: "", comment: "Zが来たらこのラインをこう消す" },
        { grid: ["___IIII__X", "__XXOO__XX", "___XOOXXXX"], percent: null, pieces: "", comment: "SはIの後に回転入れできる" },
        { grid: ["I_ZZ______", "I__ZZ___XX", "I_XXOOXXXX", "I__XOOXXXX"], percent: null, pieces: "", comment: "JZが早いときは、Oおいて" },
        { grid: ["_____S____", "__LL_SS___", "___LZZS__I", "JJ_LTZZOOI", "J__TTTIOOI", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["___IIIIZ__", "__OOJJZZ__", "__OOJXZLLL", "__XXJXXLSS", "___XXXXSSX", "XX_XXXXXXX", "X__XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "3巡目" },
        { grid: ["___IIIIZ__", "__OOJJZZ__", "__OOJXZLLL", "__XXJXXLSS", "___XXXXSSX"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ____", "___ZZJ____", "S___ZZIIII", "SS_XXXXXOO", "_SXXXXXXOO", "_LXXXXXXXX", "_LXXXXXXXX", "_LLXXXXXXX"], percent: null, pieces: "", comment: "4巡目A:火力ルート" },
        { grid: ["______LOOJ", "______LOOJ", "______LLJJ", "__________", "__________", "___ZZ_____", "S___ZZJJLL", "SS_XXXJOOL", "_S_XXXJOOL", "_XXXXXXXXX", "_XXXXXXXXX", "_XXXXXXXXX", "_XXXXXXXXX"], percent: null, pieces: "", comment: "5巡目A-1:I早いとき" },
        { grid: ["___ZZ_____", "S___ZZJJLL", "SS_XXXJOOL", "_S_XXXJOOL"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL_S___I", "___L_SS__I", "JJ_LZZSOOI", "J__XXZZOOI", "JX_XXXXXXX"], percent: null, pieces: "", comment: "6巡目場合分け:Z>S" },
        { grid: ["_________I", "_________I", "__LL_____I", "___L__S__I", "JJ_LZZSSOO", "J__XXZZSOO", "JX_XXXXXXX"], percent: null, pieces: "", comment: "S>Z O>I" },
        { grid: ["__LL______", "___LSZZ_OO", "JJ_LSSZZOO", "J__XXSIIII", "JX_XXXXXXX"], percent: null, pieces: "", comment: "S>Z I>O" },
        { grid: ["__LL______", "___LSZZ_OO"], percent: null, pieces: "", comment: "S>Z I>O" },
        { grid: ["___ZZ_IIII", "S___ZZLOOJ", "SS_XXXLOOJ", "_S_XXXLLJJ", "_XXXXXXXXX", "_XXXXXXXXX", "_XXXXXXXXX", "_XXXXXXXXX"], percent: null, pieces: "", comment: "5巡目B:I遅いとき" },
        { grid: ["_______J__", "___ZZ__JJJ", "S___ZZIIII", "SS_XXXXXOO", "_SXXXXXXOO", "_LXXXXXXXX", "_LXXXXXXXX", "_LLXXXXXXX"], percent: null, pieces: "", comment: "B-1" },
        { grid: ["LLLSSTJJOO", "ZZSSTTJXOO", "LZZXXTJXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 66.51, pieces: "", comment: "66.51%" },
        { grid: ["ISZZLLJJOO", "TSSZZLJXOO", "TTSXXLJXXX", "TXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 66.51, pieces: "", comment: "66.51%" },
        { grid: ["_________I", "_________I", "___ZZ_J__I", "S___ZZJJJI", "SS_XXXXXOO", "_SXXXXXXOO", "_LXXXXXXXX", "_LXXXXXXXX", "_LLXXXXXXX"], percent: null, pieces: "", comment: "B-2" },
        { grid: ["LLLSSTOOJX", "ZZSSTTOOJX", "LZZXXTXJJX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 61.71, pieces: "", comment: "61.71%" },
        { grid: ["LLLSSTJOOX", "ZZSSTTJJJX", "LZZXXTXOOX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 61.71, pieces: "", comment: "61.71%" },
        { grid: ["JJJSSTZZLX", "OOSSTTLLLX", "OOJXXTXZZX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 61.71, pieces: "", comment: "61.71%" },
        { grid: ["ISZZLLOOJX", "TSSZZLOOJX", "TTSXXLXJJX", "TXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 61.71, pieces: "", comment: "61.71%" },
        { grid: ["_________I", "___ZZ_OO_I", "S___ZZOOLI", "SS_XXXXXLI", "_SXXXXXXLL", "_JXXXXXXXX", "_JXXXXXXXX", "JJ_XXXXXXX"], percent: null, pieces: "", comment: "B-3" },
        { grid: ["IZLLLTOOJJ", "ZZSSTTOOJX", "ZSSXXTXXJX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXLXXXXXXX"], percent: 19.05, pieces: "", comment: "19.05%" },
        { grid: ["_________I", "_________I", "___ZZ___LI", "S___ZZLLLI", "SS_XXXXXOO", "_SXXXXXXOO", "_JXXXXXXXX", "_JXXXXXXXX", "JJ_XXXXXXX"], percent: null, pieces: "", comment: "B-4" },
        { grid: ["JJJSSTLOOX", "ZZSSTTLOOX", "IZZXXTLLXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXJXXXXXXX"], percent: 73.02, pieces: "", comment: "73.02%" },
        { grid: ["JJJSSTOOLX", "ZZSSTTLLLX", "IZZXXTOOXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXJXXXXXXX"], percent: 73.02, pieces: "", comment: "73.02%" },
        { grid: ["OOLLLTJJZX", "OOSSTTJZZX", "ISSXXTJZXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXLXXXXXXX"], percent: 73.02, pieces: "", comment: "73.02%" },
        { grid: ["OOZZLLJSSX", "OOTZZLJJJX", "ITTXXLSSXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXTXXXXXXX"], percent: 73.02, pieces: "", comment: "73.02%" },
        { grid: ["IZLLLTJJJX", "ZZSSTTOOJX", "ZSSXXTOOXX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX", "XXLXXXXXXX"], percent: 73.02, pieces: "", comment: "73.02%" },
        { grid: ["___ZZ____I", "S___ZZJJJI", "SS_XXXXXJI", "_SXXXXXX_I", "_LXXXXXXXX", "_LXXXXXXXX", "_LLXXXXXXX"], percent: null, pieces: "", comment: "B-5:Oホールド" },
        { grid: ["LLLSSTOOOO", "ZZSSTTOOOO", "LZZXXTJJJX", "IXXXXXXXJX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 40.56, pieces: "", comment: "40.56%" },
        { grid: ["ISZZLLOOOO", "TSSZZLOOOO", "TTSXXLJJJX", "TXXXXXXXJX", "IXXXXXXXXX", "IXXXXXXXXX", "IXXXXXXXXX"], percent: 40.56, pieces: "", comment: "40.56%" },
        { grid: ["________I_", "___ZZ_OOI_", "S___ZZOOIJ", "SS_XXXXXIJ", "_SXXXXXXJJ", "_LXXXXXXXX", "_LXXXXXXXX", "_LLXXXXXXX"], percent: null, pieces: "", comment: "備考" },
        { grid: ["_____S___Z", "__LL_SS_ZZ", "___LZZS_ZI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__JJJS___Z", "__LLJSS_ZZ", "___LZZS_ZI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________OO", "________OO", "__JJJS___Z", "__LLJSS_ZZ", "___LZZS_ZI", "JJ_LTZZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________OO", "________OO", "__JJJS___Z", "__LLJSS_ZZ", "___LZZS_ZI", "JJ_LTZZOOI", "J__TTTIOOI", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LL______", "___L_____I", "JJ_LT__OOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "〔図7〕" },
        { grid: ["__LL___Z__", "___L__ZZ_I", "JJ_LT_ZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LLS__Z__", "___LSSZZ_I", "JJ_LTSZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__ZZ______", "___ZZ_____", "__LLS__Z__", "___LSSZZ_I", "JJ_LTSZOOI", "J__TTTIOOI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__ZZ______", "___ZZ_____", "__LLS__Z__", "___LSSZZ_I", "JJ_LTSZOOI", "J__TTTIOOI", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__XX______", "___XXXXXXX", "I_TLSSZZXI"], percent: null, pieces: "", comment: "" },
        { grid: ["______I_LL", "______I__L", "____JJI_SL", "____JSI_SS", "__LLJSS__S", "___LZZS__I", "JJ_LTZZOOI", "J__TTTIOOI", "JTTT__IZZI", "OOT__LIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "〔図9〕" },
        { grid: ["______I_LL", "______I__L", "____JJI_SL", "____JSI_SS", "__LLJSS__S", "___LZZS__I", "JJTLTZZOOI", "JTTTTTIOOI", "OOTLLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__LLS_OO__", "___LSSOO_I", "JJ_LTSZZ_I", "J__TTTIZZI", "J___SSIZZI", "OO_SSLIJZZ", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "〔図11〕" },
        { grid: ["__LLS_OO__", "___LSSOO_I", "JJ_LTSZZ_I", "J__TTTIZZI", "OO_LLLIJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____S_OOLL", "____SSOOIL", "__XXXSXXIL", "___XXXXXIX", "XX_XXXXXIX", "X__XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["____IIIIOO", "XX___LLLOO", "XXX_XLXXXX", "X_XXXXXXXX", "__XXXXXXXX", "___XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["I___LLL___", "IJJZLS____", "IJZZTSS_OO", "IJZTTTS_OO"], percent: null, pieces: "", comment: "〔図12〕" },
        { grid: ["______JJ__", "S__ZZ_J___", "SSOOZZJ_LL", "XSOOXXX__L", "XXXXXX___L", "XXXXXXX_XX", "XXXXXXX_XX"], percent: null, pieces: "", comment: "" },
        { grid: ["__LLS__Z__", "___LSSZZ_I", "JJ_LXSZOOI", "J__XXXXOOI", "J___XXXXXI", "XX_XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "2巡目" },
        { grid: ["___LLI____", "__OOLIJJSS", "__OOLIJSSZ", "__XXXIJXZZ", "___XXXXXZX", "XX_XXXXXXX", "X__XXXXXXX", "XX_XXXXXXX"], percent: null, pieces: "", comment: "3巡目" },
        { grid: ["TTTXXXIIII", "STXXXXXXXX", "SSXXXXXXXX", "JSXXXXXXXX", "JJJXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["TTTXXXIIII", "OOXXXXXXXX", "OOXXXXXXXX", "JTXXXXXXXX", "JJJXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["LLLXXXIIII", "OOXXXXXXXX", "OOXXXXXXXX", "LTXXXXXXXX", "TTTXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["LLLXXXIIII", "LZXXXXXXXX", "ZZXXXXXXXX", "ZTXXXXXXXX", "TTTXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["SOOXXXIIII", "SSXXXXXXXX", "TSXXXXXXXX", "TTXXXXXXXX", "TOOXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["SOOXXXIIII", "SSXXXXXXXX", "JJXXXXXXXX", "JSXXXXXXXX", "JOOXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["JJJXXXIIII", "LLXXXXXXXX", "TLXXXXXXXX", "TTXXXXXXXX", "TLJXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
        { grid: ["TTTXXXIIII", "JJXXXXXXXX", "JTXXXXXXXX", "ZZXXXXXXXX", "JZZXXXXXXX"], percent: null, pieces: "", comment: "4巡目-パフェルート" },
      ],
    },
    {
      id: "gamushiro", title: "ガムシロ積み", source: "https://w.atwiki.jp/tetrismaps/pages/195.html", total: 186,
      forms: [
        { grid: ["________L_", "S______IL_", "SS____TILL", "JS_ZZTTIOO", "JJJ_ZZTIOO"], percent: null, pieces: "", comment: "〔図1〕" },
        { grid: ["I_______OO", "I_______OO", "IJJ_____LL", "IJ____SSXL", "XJTZZSSXXL", "XXTTZZXXXX", "XXTXXXXXXX", "XXX_XXXXXX"], percent: 99.09, pieces: "", comment: "99.09%" },
        { grid: ["XJIIIILLXX", "XJJJSSZLXX", "XXXSSZZLXX", "XXTTTZXXXX", "XXXTXXXXXX"], percent: 39.3, pieces: "", comment: "39.3 %" },
        { grid: ["XJIIIIOOXX", "XJJJSSOOXX", "XXXSSLLLXX", "XXTTTLXXXX", "XXXTXXXXXX"], percent: 35.0, pieces: "", comment: "35.0 %" },
        { grid: ["XIIIILLLXX", "XJJJSLOOXX", "XXXJSSOOXX", "XXTTTSXXXX", "XXXTXXXXXX"], percent: 29.2, pieces: "", comment: "29.2 %" },
        { grid: ["XOOJJTTTXX", "XOOJSSTLXX", "XXXSSLLLXX", "XXIIIIXXXX", "XXXJXXXXXX"], percent: 24.4, pieces: "", comment: "24.4 %" },
        { grid: ["XIIIIZOOXX", "XJJJZZOOXX", "XXXJZLLLXX", "XXTTTLXXXX", "XXXTXXXXXX"], percent: 23.8, pieces: "", comment: "23.8 %" },
        { grid: ["XJZZIIIIXX", "XJJJLLOOXX", "XXXZZLOOXX", "XXTTTLXXXX", "XXXTXXXXXX"], percent: 19.4, pieces: "", comment: "19.4 %" },
        { grid: ["XOOZZSLLXX", "XOOJJSSLXX", "XXXJZZSLXX", "XXIIIIXXXX", "XXXJXXXXXX"], percent: 19.0, pieces: "", comment: "19.0 %" },
        { grid: ["XOOJSSLLXX", "XOOJJJZLXX", "XXXSSZZLXX", "XXTTTZXXXX", "XXXTXXXXXX"], percent: 19.0, pieces: "", comment: "19.0 %" },
        { grid: ["XOOJJSLLXX", "XOOJTSSLXX", "XXXTTTSLXX", "XXIIIIXXXX", "XXXJXXXXXX"], percent: 17.8, pieces: "", comment: "17.8 %" },
        { grid: ["XLLLIIIIXX", "XLTTTJOOXX", "XXXSSJOOXX", "XXSSJJXXXX", "XXXTXXXXXX"], percent: 17.5, pieces: "", comment: "17.5 %" },
        { grid: ["XLLLIIIIXX", "XLSTTTOOXX", "XXXJJJOOXX", "XXSSTJXXXX", "XXXSXXXXXX"], percent: 15.6, pieces: "", comment: "15.6 %" },
        { grid: ["XOOJJSLLXX", "XOOZZSSLXX", "XXXJZZSLXX", "XXIIIIXXXX", "XXXJXXXXXX"], percent: 15.2, pieces: "", comment: "15.2 %" },
        { grid: ["XLLLIIIIXX", "XLSJJJOOXX", "XXXTTTOOXX", "XXSSTJXXXX", "XXXSXXXXXX"], percent: 13.6, pieces: "", comment: "13.6 %" },
        { grid: ["XOOIIIIJXX", "XOOZZSSJXX", "XXXTZZJJXX", "XXTTSSXXXX", "XXXTXXXXXX"], percent: 12.7, pieces: "", comment: "12.7 %" },
        { grid: ["XOOJJZZLXX", "XOOJSLLLXX", "XXXJSSZZXX", "XXTTTSXXXX", "XXXTXXXXXX"], percent: 12.0, pieces: "", comment: "12.0 %" },
        { grid: ["XIIIIZZLXX", "XJJJSLLLXX", "XXXJSSZZXX", "XXTTTSXXXX", "XXXTXXXXXX"], percent: 11.6, pieces: "", comment: "11.6 %" },
        { grid: ["XOOIIIIJXX", "XOOZZSSJXX", "XXXTSSJJXX", "XXTTZZXXXX", "XXXTXXXXXX"], percent: 10.5, pieces: "", comment: "10.5 %" },
        { grid: ["XSIIIIOOXX", "XSSTTTOOXX", "XXXJJLLLXX", "XXSJTLXXXX", "XXXJXXXXXX"], percent: 10.3, pieces: "", comment: "10.3 %" },
        { grid: ["XIIIIZOOXX", "XTTTZZOOXX", "XXXJJLLLXX", "XXTJZLXXXX", "XXXJXXXXXX"], percent: 10.3, pieces: "", comment: "10.3 %" },
        { grid: ["XOOZZJJJXX", "XOOTZZSSXX", "XXXTTSSJXX", "XXIIIIXXXX", "XXXTXXXXXX"], percent: 9.5, pieces: "", comment: "9.5 %" },
        { grid: ["XOOLLLSSXX", "XOOLZJJJXX", "XXXZZSSJXX", "XXIIIIXXXX", "XXXZXXXXXX"], percent: 9.5, pieces: "", comment: "9.5 %" },
        { grid: ["XJJJIIIIXX", "XZZSLLOOXX", "XXXSSLOOXX", "XXZZSLXXXX", "XXXJXXXXXX"], percent: 8.9, pieces: "", comment: "8.9 %" },
        { grid: ["XTTTSSZJXX", "XIIIIZZJXX", "XXXSSZJJXX", "XXTLLLXXXX", "XXXLXXXXXX"], percent: 8.9, pieces: "", comment: "8.9 %" },
        { grid: ["XTTTOOSSXX", "XIIIISSLXX", "XXXJJLLLXX", "XXTJOOXXXX", "XXXJXXXXXX"], percent: 8.8, pieces: "", comment: "8.8 %" },
        { grid: ["XTTTZZLLXX", "XIIIIZZLXX", "XXXJJSSLXX", "XXTJSSXXXX", "XXXJXXXXXX"], percent: 8.6, pieces: "", comment: "8.6 %" },
        { grid: ["XTTTIIIIXX", "XJJJLLOOXX", "XXXJZLOOXX", "XXTZZLXXXX", "XXXZXXXXXX"], percent: 8.4, pieces: "", comment: "8.4 %" },
        { grid: ["XTTTSSOOXX", "XIIIIJOOXX", "XXXSSJJJXX", "XXTLLLXXXX", "XXXLXXXXXX"], percent: 8.4, pieces: "", comment: "8.4 %" },
        { grid: ["XSTTTZOOXX", "XSSTZZOOXX", "XXXJJLLLXX", "XXSJZLXXXX", "XXXJXXXXXX"], percent: 8.1, pieces: "", comment: "8.1 %" },
        { grid: ["XJTTTZOOXX", "XJJJZZOOXX", "XXXSSLLLXX", "XXSSZLXXXX", "XXXTXXXXXX"], percent: 8.1, pieces: "", comment: "8.1 %" },
        { grid: ["XSTTTLLLXX", "XSSTZLOOXX", "XXXJJJOOXX", "XXSZZJXXXX", "XXXZXXXXXX"], percent: 8.1, pieces: "", comment: "8.1 %" },
        { grid: ["XSLLIIIIXX", "XSSJJJOOXX", "XXXTTTOOXX", "XXSLTJXXXX", "XXXLXXXXXX"], percent: 8.1, pieces: "", comment: "8.1 %" },
        { grid: ["XSTTTLOOXX", "XSSLLLOOXX", "XXXJIIIIXX", "XXSJJJXXXX", "XXXTXXXXXX"], percent: 7.6, pieces: "", comment: "7.6 %" },
        { grid: ["XIIIILLLXX", "XTTTZLOOXX", "XXXJJJOOXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 7.6, pieces: "", comment: "7.6 %" },
        { grid: ["XIIIIZOOXX", "XJJJZZOOXX", "XXXSSLLLXX", "XXSSZLXXXX", "XXXJXXXXXX"], percent: 7.6, pieces: "", comment: "7.6 %" },
        { grid: ["XSTTTJJJXX", "XSSIIIIJXX", "XXXOOLLLXX", "XXSOOLXXXX", "XXXTXXXXXX"], percent: 7.6, pieces: "", comment: "7.6 %" },
        { grid: ["XSIIIILLXX", "XSSTTTZLXX", "XXXJJZZLXX", "XXSJTZXXXX", "XXXJXXXXXX"], percent: 7.6, pieces: "", comment: "7.6 %" },
        { grid: ["XTTTSLLLXX", "XJJJSSOOXX", "XXXJZSOOXX", "XXTZZLXXXX", "XXXZXXXXXX"], percent: 7.1, pieces: "", comment: "7.1 %" },
        { grid: ["XSLLIIIIXX", "XSSLZJOOXX", "XXXZZJOOXX", "XXSZJJXXXX", "XXXLXXXXXX"], percent: 6.7, pieces: "", comment: "6.7 %" },
        { grid: ["XJJJIIIIXX", "XTTTSSOOXX", "XXXSSLOOXX", "XXTLLLXXXX", "XXXJXXXXXX"], percent: 6.7, pieces: "", comment: "6.7 %" },
        { grid: ["XSLLIIIIXX", "XSSJJJOOXX", "XXXZZJOOXX", "XXSLZZXXXX", "XXXLXXXXXX"], percent: 6.7, pieces: "", comment: "6.7 %" },
        { grid: ["XTTTZSLLXX", "XIIIISSLXX", "XXXJJJSLXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 6.7, pieces: "", comment: "6.7 %" },
        { grid: ["XSLLIIIIXX", "XSSTTTOOXX", "XXXJJJOOXX", "XXSLTJXXXX", "XXXLXXXXXX"], percent: 6.3, pieces: "", comment: "6.3 %" },
        { grid: ["XJSZZTLLXX", "XJJJTTTLXX", "XXXIIIILXX", "XXSSZZXXXX", "XXXSXXXXXX"], percent: 6.3, pieces: "", comment: "6.3 %" },
        { grid: ["XJTTTLLLXX", "XJJJSSOOXX", "XXXSSLOOXX", "XXIIIIXXXX", "XXXTXXXXXX"], percent: 6.3, pieces: "", comment: "6.3 %" },
        { grid: ["XSZZLLOOXX", "XSSZZLOOXX", "XXXTIIIIXX", "XXSTTLXXXX", "XXXTXXXXXX"], percent: 6.3, pieces: "", comment: "6.3 %" },
        { grid: ["XSJJJZOOXX", "XSSIZZOOXX", "XXXIZLLLXX", "XXSIJLXXXX", "XXXIXXXXXX"], percent: 6.0, pieces: "", comment: "6.0 %" },
        { grid: ["XOOZZSSJXX", "XOOIIIIJXX", "XXXTZZJJXX", "XXTTSSXXXX", "XXXTXXXXXX"], percent: 6.0, pieces: "", comment: "6.0 %" },
        { grid: ["XOOZZSSJXX", "XOOIIIIJXX", "XXXTSSJJXX", "XXTTZZXXXX", "XXXTXXXXXX"], percent: 6.0, pieces: "", comment: "6.0 %" },
        { grid: ["XTTTZLLLXX", "XIIIILOOXX", "XXXJJJOOXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 5.9, pieces: "", comment: "5.9 %" },
        { grid: ["XSIIIILLXX", "XSSJJOOLXX", "XXXZZOOLXX", "XXSJZZXXXX", "XXXJXXXXXX"], percent: 5.7, pieces: "", comment: "5.7 %" },
        { grid: ["XSIIIILLXX", "XSSZZOOLXX", "XXXJJOOLXX", "XXSJZZXXXX", "XXXJXXXXXX"], percent: 5.7, pieces: "", comment: "5.7 %" },
        { grid: ["XSTTTJJJXX", "XSSOOZZJXX", "XXXOOLZZXX", "XXSLLLXXXX", "XXXTXXXXXX"], percent: 5.4, pieces: "", comment: "5.4 %" },
        { grid: ["XJJJIIIIXX", "XZZSTTTLXX", "XXXSSLLLXX", "XXZZSTXXXX", "XXXJXXXXXX"], percent: 5.2, pieces: "", comment: "5.2 %" },
        { grid: ["XIIIITTTXX", "XJJJOOTLXX", "XXXSSLLLXX", "XXSSOOXXXX", "XXXJXXXXXX"], percent: 5.2, pieces: "", comment: "5.2 %" },
        { grid: ["XOOJJZZLXX", "XOOTTTZZXX", "XXXJTLLLXX", "XXIIIIXXXX", "XXXJXXXXXX"], percent: 4.8, pieces: "", comment: "4.8 %" },
        { grid: ["XIIIISLLXX", "XTTTZSSLXX", "XXXJJJSLXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 4.3, pieces: "", comment: "4.3 %" },
        { grid: ["XSIIIIZJXX", "XSSOOZZJXX", "XXXOOZJJXX", "XXSLLLXXXX", "XXXLXXXXXX"], percent: 4.1, pieces: "", comment: "4.1 %" },
        { grid: ["XSTTTLLLXX", "XSSZZLOOXX", "XXXJZZOOXX", "XXSJJJXXXX", "XXXTXXXXXX"], percent: 3.8, pieces: "", comment: "3.8 %" },
        { grid: ["XSJJJLLLXX", "XSSIJZOOXX", "XXXIZZOOXX", "XXSIZLXXXX", "XXXIXXXXXX"], percent: 3.8, pieces: "", comment: "3.8 %" },
        { grid: ["XOOLLLZJXX", "XOOSSZZJXX", "XXXTTTJJXX", "XXSSTZXXXX", "XXXLXXXXXX"], percent: 3.8, pieces: "", comment: "3.8 %" },
        { grid: ["XJTTTZZLXX", "XJJJSSZZXX", "XXXSSLLLXX", "XXIIIIXXXX", "XXXTXXXXXX"], percent: 3.2, pieces: "", comment: "3.2 %" },
        { grid: ["XSTTTLLLXX", "XSSTZJJJXX", "XXXIIIIJXX", "XXSZZLXXXX", "XXXZXXXXXX"], percent: 2.9, pieces: "", comment: "2.9 %" },
        { grid: ["XTTTLLOOXX", "XJJJIIIIXX", "XXXJZLOOXX", "XXTZZLXXXX", "XXXZXXXXXX"], percent: 2.9, pieces: "", comment: "2.9 %" },
        { grid: ["I_________", "I_____OO__", "IJJ___OOLL", "IJ____SSXL", "XJTZZSSXXL", "XXTTZZXXXX", "XXTXXXXXXX", "XXX_XXXXXX"], percent: 49.37, pieces: "", comment: "49.37%" },
        { grid: ["XIIIILLLOO", "XJJJSLXXOO", "XXXJSSXXXX", "XXTTTSXXXX", "XXXTXXXXXX"], percent: 9.1, pieces: "", comment: "9.1 %" },
        { grid: ["XLLLIIIIOO", "XLSTTTXXOO", "XXXJJJXXXX", "XXSSTJXXXX", "XXXSXXXXXX"], percent: 9.0, pieces: "", comment: "9.0 %" },
        { grid: ["XJZZIIIIOO", "XJJJLLXXOO", "XXXZZLXXXX", "XXTTTLXXXX", "XXXTXXXXXX"], percent: 8.8, pieces: "", comment: "8.8 %" },
        { grid: ["XLLLIIIIOO", "XLSJJJXXOO", "XXXTTTXXXX", "XXSSTJXXXX", "XXXSXXXXXX"], percent: 8.0, pieces: "", comment: "8.0 %" },
        { grid: ["XLLLIIIIOO", "XLTTTJXXOO", "XXXSSJXXXX", "XXSSJJXXXX", "XXXTXXXXXX"], percent: 7.7, pieces: "", comment: "7.7 %" },
        { grid: ["XSLLIIIIOO", "XSSJJJXXOO", "XXXTTTXXXX", "XXSLTJXXXX", "XXXLXXXXXX"], percent: 7.1, pieces: "", comment: "7.1 %" },
        { grid: ["XSTTTLLLOO", "XSSTZLXXOO", "XXXJJJXXXX", "XXSZZJXXXX", "XXXZXXXXXX"], percent: 7.1, pieces: "", comment: "7.1 %" },
        { grid: ["XJJJIIIIOO", "XZZSLLXXOO", "XXXSSLXXXX", "XXZZSLXXXX", "XXXJXXXXXX"], percent: 5.7, pieces: "", comment: "5.7 %" },
        { grid: ["XSLLIIIIOO", "XSSTTTXXOO", "XXXJJJXXXX", "XXSLTJXXXX", "XXXLXXXXXX"], percent: 5.2, pieces: "", comment: "5.2 %" },
        { grid: ["XJJJIIIIOO", "XTTTSSXXOO", "XXXSSLXXXX", "XXTLLLXXXX", "XXXJXXXXXX"], percent: 4.8, pieces: "", comment: "4.8 %" },
        { grid: ["XIIIILLLOO", "XTTTZLXXOO", "XXXJJJXXXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 4.8, pieces: "", comment: "4.8 %" },
        { grid: ["XSLLIIIIOO", "XSSJJJXXOO", "XXXZZJXXXX", "XXSLZZXXXX", "XXXLXXXXXX"], percent: 4.8, pieces: "", comment: "4.8 %" },
        { grid: ["XSLLIIIIOO", "XSSLZJXXOO", "XXXZZJXXXX", "XXSZJJXXXX", "XXXLXXXXXX"], percent: 4.8, pieces: "", comment: "4.8 %" },
        { grid: ["XTTTZLLLOO", "XIIIILXXOO", "XXXJJJXXXX", "XXTZZJXXXX", "XXXZXXXXXX"], percent: 4.1, pieces: "", comment: "4.1 %" },
      ],
    },
    {
      id: "tsdopener", title: "開幕TSD", source: "https://w.atwiki.jp/tetrismaps/pages/200.html", total: 95,
      forms: [
        { grid: ["L_________", "L_________", "LL_IIII___"], percent: null, pieces: "", comment: "" },
        { grid: ["L__ZZ_____", "L___ZZ____", "LL_IIII___"], percent: null, pieces: "", comment: "" },
        { grid: ["L__ZZ_S___", "L___ZZSS__", "LL_IIIIS__"], percent: null, pieces: "", comment: "" },
        { grid: ["L__ZZ_S___", "L___ZZSSOO", "LL_IIIISOO"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ____", "L__ZZJS___", "L___ZZSSOO", "LL_IIIISOO"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ____", "L__ZZJS___"], percent: null, pieces: "", comment: "" },
        { grid: ["S_________", "SS_JJJ____", "LS_ZZJS___"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_JJJ____", "LS_ZZJS___"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_JJJ_OO_", "LS_ZZJSOO_"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ____I", "S___ZZ___I", "SS_JJJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ____I", "S___ZZLLLI", "SS_JJJLOOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ____I", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ____", "___ZZJ___I", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["S_________", "SS_JJJ____", "_S_ZZJ___I", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["S_________", "SS_JJJ_OO_", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_JJJ_OO_", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZLLL_", "SS_JJJLOO_", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ____", "___ZZJ____", "S___ZZLLL_", "SS_JJJLOO_", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ___I", "___ZZJ___I", "S___ZZLLLI", "SS_JJJLOOI", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ___I", "___ZZJ___I", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "____ZZ____", "___JJJ___I", "___ZZJ___I", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_JJJ___I", "_S_ZZJ___I", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_JJJ_OOI", "_S_ZZJ_OOI", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["_________I", "_________I", "___ZZ____I", "S___ZZ___I", "SS_JJJ_OOI", "_S_ZZJ_OOI", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["_________I", "_________I", "___ZZ____I", "S___ZZLLLI", "SS_JJJLOOI", "_S_ZZJ_OOI", "_S_ZZJ_OOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "以下ループ" },
        { grid: ["L_________", "L_________", "LL_JJJ____", "L__ZZJS___"], percent: null, pieces: "", comment: "" },
        { grid: ["______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "L__ZZ_XXXX", "L___ZZXXXX", "LL_JJJXXXX", "L__ZZJSXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "L__ZZ_XXXX", "L__ZZJSXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "L_____XXXX", "L_____XXXX", "LL____XXXX", "L__ZZ_XXXX", "L__ZZJSXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "L_____XXXX", "L_____XXXX", "LL_JJJXXXX", "L__ZZJXXXX", "L__ZZJSXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "______XXXX", "L__ZZ_XXXX", "L___ZZXXXX", "LL_JJJXXXX", "L__ZZJXXXX", "L__ZZJSXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["_________J", "_________J", "L__ZZ_S_JJ", "LTTTZZSSOO", "LLTIIIISOO"], percent: null, pieces: "", comment: "" },
        { grid: ["_________J", "_________J", "L__ZZ_S_JJ"], percent: null, pieces: "", comment: "" },
        { grid: ["OOLLL__IJJ", "OOLSS__IJJ", "ZZSS___IJJ", "LZZZZ_SIJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["OOLLL__IJJ", "OOLSS__IJJ", "ZZSSTTTIJJ", "LZZZZTSIJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["OOLLL__IJJ", "OOLSS__IJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["JJJZZIIIII", "LSJZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["_______J__", "L__ZZ_SJJJ", "L___ZZSSOO", "LL_IIIISOO"], percent: null, pieces: "", comment: "" },
        { grid: ["_______J__", "L__ZZ_SJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["LLS____OOJ", "LSS____OOJ", "LSZZ___JJJ", "LZZZZ_SJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["LLSIIIIOOJ", "LSSIIIIOOJ", "LSZZTTTJJJ", "LZZZZTSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["LLSOOJJOOJ", "LSSOOTJOOJ", "LSZZTTJJJJ", "LZZZZTSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["S_________", "SS________", "LS_ZZ_S___"], percent: null, pieces: "", comment: "" },
        { grid: ["S_________", "SS_JJJ_OO_", "LS_ZZJSOO_"], percent: null, pieces: "", comment: "" },
        { grid: ["S_____LLL_", "SS_JJJLOO_", "LS_ZZJSOO_"], percent: null, pieces: "", comment: "" },
        { grid: ["_________I", "S_____LLLI", "SS_JJJLOOI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["_Z________", "ZZ_JJJ____", "Z__ZZJ___I", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["__XXXXXXXX", "___XXXXXXX", "JJ_XXXXXXX", "J__XXXXXXX", "JZ_XXXXXXX", "ZZ_JJJXXXX", "Z__ZZJXXXI", "LS_ZZJSOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_XXX____", "XS_XXXX___"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "S___ZZ____", "SS_XXX_OO_", "XS_XXXXOO_"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ____I", "S___ZZ___I", "SS_XXX_OOI", "XS_XXXXOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ____I", "S___ZZLLLI", "SS_XXXLOOI", "XS_XXXXOOI"], percent: null, pieces: "", comment: "" },
        { grid: ["I_________", "I_____L___", "I__XXXL___", "I__XXXLL_X", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["I_________", "I_____L___", "IOOXXXL___", "IOOXXXLL_X", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______S___", "I_____SS__", "I_____LS__", "IOOXXXL___", "IOOXXXLL_X", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["______S___", "I__J__SS__", "I__JJJLS__", "IOOXXXL___", "IOOXXXLL_X", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_S___", "I__JZZSS__", "I__JJJLS__", "IOOXXXL___", "IOOXXXLL_X", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["LL_XX_X___", "XL_XXXXXOO", "XL_XXXXXOO", "XX_XXXXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_____", "____ZZ____", "___IIII___"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_S___", "____ZZSS__", "___IIIIS__"], percent: null, pieces: "", comment: "" },
        { grid: ["___ZZ_S___", "____ZZSSOO", "___IIIISOO"], percent: null, pieces: "", comment: "" },
        { grid: ["___JJJ_J__", "L__ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________OO", "___JJJ_JOO", "L__ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_______LLL", "_______LOO", "___JJJ_JOO", "L__ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["______I___", "______ILLL", "______ILOO", "___JJJIJOO", "L__ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["______I___", "___ZZ_ILLL", "____ZZILOO", "___JJJIJOO", "L__ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["______I___", "___ZZ_ILLL", "S___ZZILOO", "SS_JJJIJOO", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["______I___", "___ZZ_ILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["__ZZ______", "___ZZ_I___", "___ZZ_ILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["I_________", "I_ZZ______", "I__ZZ_I___", "I__ZZ_ILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["OO___XXXXX", "OO___XXXXX", "I____XXXXX", "I_ZZXXXXXX", "I__ZZXIXXX", "I__ZZXILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_XX_______", "_X________", "OO_LLXXXXX", "OO__LXXXXX", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["_______OO_", "______IOO_", "___ZZ_ILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["____LL_OO_", "_____LIOO_", "___ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________S_", "________SS", "____LL_OOS", "_____LIOO_", "___ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________S_", "________SS", "__ZZLL_OOS", "___ZZLIOO_", "___ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "" },
        { grid: ["________S_", "_JJ_____SS", "_JZZLL_OOS", "_J_ZZLIOO_", "___ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "ここからはアドリブ" },
        { grid: ["________S_", "IJJ_____SS", "IJZZLL_OOS", "IJ_ZZLIOO_", "I__ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "ここからはアドリブ" },
        { grid: ["__LL______", "___L____S_", "IJJL____SS", "IJZZLL_OOS", "IJ_ZZLIOO_", "I__ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "ここからはアドリブ" },
        { grid: ["__LL_Z____", "___LZZ__S_", "IJJLZ___SS", "IJZZLL_OOS", "IJ_ZZLIOO_", "I__ZZLILLL", "LS_ZZJSJJJ"], percent: null, pieces: "", comment: "ここからはアドリブ" },
      ],
    },
    {
      id: "gasshotsd", title: "合掌TSDパフェ", source: "https://w.atwiki.jp/tetrismaps/pages/322.html", total: 13,
      forms: [
        { grid: ["IJJ______L", "IJ___ZSLLL", "IJT_ZZSSOO", "ITTTZ__SOO"], percent: null, pieces: "", comment: "1巡目" },
        { grid: ["XXXJJJLLLX", "XXXXXJLXXX"], percent: null, pieces: "", comment: "確率5.71%" },
        { grid: ["OO_______Z", "OO______ZZ", "XXX_____ZX", "XX___XXXXX", "XXX_XXXXXX", "XXXXX__XXX"], percent: null, pieces: "", comment: "2巡目B:6段パフェルート" },
        { grid: ["OOS______Z", "OOSS____ZZ", "XXXS____ZX", "XXXXX__XXX"], percent: null, pieces: "", comment: "2巡目B:6段パフェルート" },
        { grid: ["XXXLLIIJJX", "XXXXLIIJXX", "XXXXLIIJXX", "XXXXXIIXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXLLIIIIX", "XXXXLJJJXX", "XXXXLOOJXX", "XXXXXOOXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXLLIIIIX", "XXXXLJSSXX", "XXXXLJJJXX", "XXXXXSSXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXIIIIJJX", "XXXXZZLJXX", "XXXXLLLJXX", "XXXXXZZXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXTTTIJJX", "XXXXLLIJXX", "XXXXTLIJXX", "XXXXXLIXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXLLLLJJX", "XXXXLJJJXX", "XXXXLJLJXX", "XXXXXJLXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["XXXLLJJJJX", "XXXXLLLJXX", "XXXXLJLJXX", "XXXXXJLXXX"], percent: 100.0, pieces: "", comment: "100%" },
        { grid: ["I______JJJ", "IL_____ZSJ", "IL____ZZSS", "ILL___ZOOS", "XXX____OOX", "XX___XXXXX", "XXX_XXXXXX", "XXXXX__XXX"], percent: null, pieces: "", comment: "確定TSD（SZO巡回）" },
        { grid: ["I______JJJ", "IL_____ZSJ", "IL____ZZSS", "ILL___ZOOS", "XXX____OOX", "XXXXX__XXX"], percent: null, pieces: "", comment: "" },
      ],
    },
    {
      id: "opener_pc", title: "開幕パフェ積み", source: "https://w.atwiki.jp/tetrismaps/pages/202.html", total: 96,
      forms: [
        { grid: ["_______OO_", "_______OOL", "_______LLL"], percent: null, pieces: "", comment: "" },
        { grid: ["_______JJJ", "_______OOJ", "_______OOL", "_______LLL"], percent: null, pieces: "", comment: "" },
        { grid: ["______IJJJ", "______IOOJ", "______IOOL", "______ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["______IJJJ", "______IOOJ", "__SS__IOOL", "_SS___ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["______IJJJ", "T_____IOOJ", "TTSS__IOOL", "TSS___ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["ZZ____IJJJ", "TZZ___IOOJ", "TTSS__IOOL", "TSS___ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["ZZ____IJJJ", "TZZ_J_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["__S_______", "ZZSS__IJJJ", "TZZSJ_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["_____Z____", "__S_ZZ____", "ZZSSZ_IJJJ", "TZZSJ_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["OO___Z____", "OOS_ZZ____", "ZZSSZ_IJJJ", "TZZSJ_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["OO___Z____", "OOS_ZZIIII", "ZZSSZ_IJJJ", "TZZSJ_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["__L_______", "LLL_______", "OO___ZXXXX", "OOS_ZZIIII", "ZZSSZ_IJJJ", "TZZSJ_IOOJ", "TTSSJ_IOOL", "TSSJJ_ILLL"], percent: null, pieces: "", comment: "" },
        { grid: ["JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "〔図2〕はいどうもこんにちは・。・" },
        { grid: ["__TTTTTT__", "__TTTTTT__", "____TT____", "____TT____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "・初手Tの場合" },
        { grid: ["JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "初手Tは2通りあるよ・。・" },
        { grid: ["JJJ_____SS", "OOLTTTZZTT", "LLL_T__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOLTTTZZTT", "LLL_T__ZZT"], percent: null, pieces: "", comment: "といっても" },
        { grid: ["JJJLLL__SS", "LLLLT__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ___SSSS", "LLL_TSSZZT"], percent: null, pieces: "", comment: "TLSとTSLの違いだけど" },
        { grid: ["JJJLLLSSSS", "LLLLTSSZZT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJLLLSSSS", "LLLLTSSZZT"], percent: null, pieces: "", comment: "・。・" },
        { grid: ["OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "OOOOOOOOOO", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "初手Oミノの場合" },
        { grid: ["JJJ_____SS", "OOL___ZZTT", "LLL____ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "Oミノもパターンは2つあるよ" },
        { grid: ["JJJJJJ__SS", "OOLOOJZZTT", "LLLOO__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJJJ___SS", "OOLJOOZZTT", "LLLJOO_ZZT"], percent: null, pieces: "", comment: "OJSとOJTの2通りだね・。・" },
        { grid: ["JJJJJJSSSS", "LLLOOSSZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJJJTTTSS", "LLLJOOTZZT"], percent: null, pieces: "", comment: "OJSとOJTの2通りだね・。・" },
        { grid: ["JJJJJJSSSS", "OOJIIIISST", "OOLOOJZZTT", "LLLOOSSZZT"], percent: null, pieces: "", comment: "OJSは特有のパターンだけど" },
        { grid: ["JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLL____ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "OJTは" },
        { grid: ["JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLLIIIIZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "Iミノをこう消してもできるけど" },
        { grid: ["JJJ_____SS", "OOJ_OO_SST", "OOL_OOZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOL_OOZZTT", "LLL_OO_ZZT"], percent: null, pieces: "", comment: "下はSD0回でできるのに対して" },
        { grid: ["JJJJJ___SS", "OOJJOO_SST", "OOLJOOZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJJJ___SS", "OOLJOOZZTT", "LLLJOO_ZZT"], percent: null, pieces: "", comment: "下はSD0回でできるのに対して" },
        { grid: ["JJJJJTTTSS", "OOJJOOTSST", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJJJTTTSS", "LLLJOOTZZT"], percent: null, pieces: "", comment: "上はIミノ寝かす時に1度SDをするから" },
        { grid: ["LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "さて次は" },
        { grid: ["_____JJ___", "_____JJ___", "_____JJ___", "_____JJ___", "___JJJJ___", "___JJJJ___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "Jミノのパーターンです" },
        { grid: ["__JJJJJJ__", "__JJJJJJ__", "______JJ__", "______JJ__", "__________", "LLL_____SS", "JOOJJJZZTT", "JJJ__J_ZZT", "__________", "__________", "__________", "LLL_____SS", "JOOJJJZZTT", "JJJ__J_ZZT"], percent: null, pieces: "", comment: "JTOとJOTのパターン・。・" },
        { grid: ["LLL__TTTSS", "JJJ__JTZZT", "__________", "__________", "__________", "LLLOO___SS", "JJJOOJ_ZZT"], percent: null, pieces: "", comment: "JTOとJOTのパターン・。・" },
        { grid: ["LLLOOTTTSS", "JJJOOJTZZT", "__________", "__________", "__________", "LLLOOTTTSS", "JJJOOJTZZT"], percent: null, pieces: "", comment: "JTOとJOTのパターン・。・" },
        { grid: ["JJJ_____SS", "OOJ____SST", "OOL___ZZTT", "LLLIIIIZZT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "この2つも" },
        { grid: ["JJJ_____SS", "OOJJJJ_SST", "OOL__JZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOLJJJZZTT", "LLL__J_ZZT"], percent: null, pieces: "", comment: "やっぱりソフドロの差で" },
        { grid: ["JJJOOTTTSS", "OOLOOJZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "JJJOOTTTSS", "LLLOOJTZZT"], percent: null, pieces: "", comment: "しかも上はOTだとできないという" },
        { grid: ["___JJJJ___", "___JJJJ___", "___JJ_____", "___JJ_____", "___JJ_____", "___JJ_____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "この向き・。・" },
        { grid: ["___JJJJ___", "___JJJJ___", "___JJ_____", "___JJ_____", "___JJ_____", "___JJ_____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "JJJJJZ__SS", "LLLJZ__ZZT"], percent: null, pieces: "", comment: "普通においてくれた方が" },
        { grid: ["___JJJJ___", "___JJJJ___", "___JJ_____", "___JJ_____", "___JJ_____", "___JJ_____"], percent: null, pieces: "", comment: "コンボも続くのでいいです" },
        { grid: ["___JJ_____", "___JJ_____", "___JJJJJJ_", "___JJJJJJ_", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "次はこの向き・。・" },
        { grid: ["LLL_____SS", "OOL____SST", "OOJ___ZZTT", "JJJ____ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLZZTTTSS", "JJJJJJTZZT"], percent: null, pieces: "", comment: "" },
        { grid: ["LLL_____SS", "OOL____SST", "OOJ___ZZTT", "JJJIIIIZZT", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "OOLIIIISST", "OOJ___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "これもIミノ寝かせ2パターンで" },
        { grid: ["LLL_____SS", "OOLJ___SST", "OOJJJJZZTT", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "OOJJ__ZZTT", "JJJJJJ_ZZT"], percent: null, pieces: "", comment: "やっぱりソフドロの差で" },
        { grid: ["LLLZZTTTSS", "OOLJZZTSST", "__________", "__________", "__________", "__________", "__________", "LLLZZTTTSS", "JJJJJJTZZT"], percent: null, pieces: "", comment: "す！・。・！" },
        { grid: ["_____JJ___", "_____JJ___", "_____JJ___", "_____JJ___", "___JJJJ___", "___JJJJ___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOO____SST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "あとはこの向きだけど" },
        { grid: ["___LL_____", "___LL_____", "___LL_____", "___LL_____", "___LLLL___", "___LLLL___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOO____SST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "L！・。・！" },
        { grid: ["____LL_L__", "_____L_L__", "_____L_LL_", "___L______", "_LLL_LLL__", "_____L____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOO____SST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "また向きごとに分けていきます" },
        { grid: ["____LL_L__", "_____L_L__", "_____L_LL_", "___L______", "_LLL_LLL__", "_____L____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "まずは" },
        { grid: ["_____LLL__", "_____L____", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "この向き・。・" },
        { grid: ["LLL_____SS", "JJJL___ZZT", "__________", "__________", "LLL_____SS", "JJJL___ZZT", "__________", "__________", "LLL_____SS", "JJJL___ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "JJJL___ZZT"], percent: null, pieces: "", comment: "LTS LST LTZ LZTの" },
        { grid: ["LLL__TTTSS", "JJJL__TZZT", "__________", "__________", "LLLZZ___SS", "JJJLZZ_ZZT", "__________", "__________", "LLLTTT__SS", "JJJLT__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "LLL___SSSS", "JJJL_SSZZT"], percent: null, pieces: "", comment: "LTS LST LTZ LZTの" },
        { grid: ["LLLZZTTTSS", "JJJLZZTZZT", "__________", "__________", "LLLZZTTTSS", "JJJLZZTZZT", "__________", "__________", "LLLTTTSSSS", "JJJLTSSZZT", "__________", "__________", "__________", "__________", "__________", "__________", "LLLTTTSSSS", "JJJLTSSZZT"], percent: null, pieces: "", comment: "4通りで消せます！" },
        { grid: ["LLL_____SS", "LOO____SST", "JOO___ZZTT", "JJJIIIIZZT", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "これでも消せますが" },
        { grid: ["LLLL____SS", "LOOL___SST", "JOOLL_ZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "JOOLLLZZTT", "JJJL___ZZT"], percent: null, pieces: "", comment: "下が早いです" },
        { grid: ["LLLLSTTTSS", "LOOLSSTSST", "__________", "__________", "__________", "__________", "__________", "__________", "LLLTTTSSSS", "JJJLTSSZZT"], percent: null, pieces: "", comment: "こんなに便利だったんですね・。・" },
        { grid: ["___LL_____", "___LL_____", "___LL_____", "___LL_____", "___LLLL___", "___LLLL___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "OOLIIIISST", "OOJ___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "次はこの向き・。・" },
        { grid: ["LLLL____SS", "OOJL__ZZTT", "JJJLL__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLL____SS", "OOJL__ZZTT", "JJJLL__ZZT"], percent: null, pieces: "", comment: "JZIとJIZのパターン" },
        { grid: ["LLLLIIIISS", "OOJL__ZZTT", "JJJLL__ZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLL____SS", "OOJLZZZZTT", "JJJLLZZZZT"], percent: null, pieces: "", comment: "この2つは" },
        { grid: ["LLLLOOSSSS", "JJJLLSSZZT"], percent: null, pieces: "", comment: "このOSの回転入れは" },
        { grid: ["JJJ_____SS", "OOJIIIISST", "OOL___ZZTT", "LLL____ZZT"], percent: null, pieces: "", comment: "まだあるね・。・" },
        { grid: ["JJJLSTTTSS", "LLLLLSTZZT"], percent: null, pieces: "", comment: "LSTのパターン" },
        { grid: ["LLL_____SS", "LOO____SST", "JOO___ZZTT", "JJJIIIIZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "やっぱり" },
        { grid: ["LLLL____SS", "LOOL___SST", "JOOLL_ZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLL____SS", "JOOL__ZZTT", "JJJLL__ZZT"], percent: null, pieces: "", comment: "やっぱり" },
        { grid: ["LLLLS___SS", "LOOLSS_SST", "JOOLLSZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLLS___SS", "JOOLSSZZTT", "JJJLLS_ZZT"], percent: null, pieces: "", comment: "ソフドロの差で" },
        { grid: ["LLLLSTTTSS", "LOOLSSTSST", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLLSTTTSS", "JJJLLSTZZT"], percent: null, pieces: "", comment: "下が早いです" },
        { grid: ["______LL__", "______LL__", "__LLLLLL__", "__LLLLLL__", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "LOOIIIISST", "JOO___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "さて次はこの向き・。・" },
        { grid: ["______LL__", "______LL__", "__LLLLLL__", "__LLLLLL__", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLOOTTTSS", "JJJLLLTZZT"], percent: null, pieces: "", comment: "LOTのパターン" },
        { grid: ["LLL_____SS", "LOO__L_SST", "JOOLLLZZTT", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "JOO__LZZTT", "JJJLLL_ZZT"], percent: null, pieces: "", comment: "ソフドロの差で下が勝つけど" },
        { grid: ["LLLOOTTTSS", "LOOOOLTSST", "__________", "__________", "__________", "__________", "__________", "__________", "LLLOOTTTSS", "JJJLLLTZZT"], percent: null, pieces: "", comment: "注意してね・。・" },
        { grid: ["___LLLL___", "___LLLL___", "_____LL___", "_____LL___", "_____LL___", "_____LL___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "OOLIIIISST", "OOJ___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "さああとはこの向きだけど" },
        { grid: ["_IIII_____", "__________", "___ZZ_____", "____ZZ____", "__________", "______SS__", "_____SS___"], percent: null, pieces: "", comment: "この子達まだ使ってないけど" },
        { grid: ["_IIII_____", "__________", "___ZZ_____", "____ZZ____", "__________", "______SS__", "_____SS___", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLL_____SS", "OOLIIIISST", "OOJ___ZZTT", "JJJ____ZZT"], percent: null, pieces: "", comment: "実は" },
        { grid: ["ZZ________", "_ZZ_______", "__________", "__________", "__________", "JJJOOLLLSS", "OOLOOLZZTT"], percent: null, pieces: "", comment: "カウントはしません" },
        { grid: ["LLLIJJ__SS", "LOOIJ__SST", "JJJIJZZZZT", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLJJZ__SS", "JOOJZZZZTT", "JJJJZ__ZZT"], percent: null, pieces: "", comment: "コンボが早くつながるので" },
        { grid: ["LLLIJJSSSS", "LOOIJSSSST", "__________", "__________", "__________", "__________", "__________", "__________", "__________", "LLLJJZSSSS", "JJJJZSSZZT"], percent: null, pieces: "", comment: "コンボが早くつながるので" },
        { grid: ["ZZ____JJLL", "TZZ___JOOL", "TTSS__JOOL", "TSS___IIII"], percent: null, pieces: "", comment: "〔図4〕王道パターン" },
        { grid: ["________OO", "________OO", "ZZ____JJLL", "TZZ___JOOL", "TTSS__JOOL", "TSS___IIII"], percent: null, pieces: "", comment: "王道パターン" },
        { grid: ["________OO", "____IIIIOO", "ZZ____JJLL", "TZZ___JOOL", "TTSS__JOOL", "TSS___IIII"], percent: null, pieces: "", comment: "王道パターン" },
        { grid: ["______S___", "______SS__", "_______SOO", "____IIIIOO", "ZZ____JJLL", "TZZ___JOOL", "TTSS__JOOL", "TSS___IIII"], percent: null, pieces: "", comment: "王道パターン" },
        { grid: ["______S___", "______SS__", "_______SOO", "___JIIIIOO", "ZZ_JJJJJLL", "TZZ___JOOL", "TTSS__JOOL", "TSS___IIII"], percent: null, pieces: "", comment: "王道パターン" },
      ],
    },
    {
      id: "mountainous2", title: "山岳積み2号", source: "https://w.atwiki.jp/tetrismaps/pages/455.html", total: 9,
      forms: [
        { grid: ["IS________", "ISS____T__", "IJS_ZZTTOO", "IJJJ_ZZTOO"], percent: null, pieces: "", comment: "Lホールド確定" },
        { grid: ["LL_______I", "LL_______I", "LLJJ_____I", "LLJ____SSI", "XXJ_ZZSSOO", "XXX__ZZXOO", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "O→SI(99.09%)" },
        { grid: ["JJOO______", "JSOO__L__I", "JSS___LLLI", "XXS_ZZLLLI", "XXX__ZZXLI", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "S→O(97.94%)" },
        { grid: ["_SS_______", "SS________", "OOJJ__L__I", "OOJ___LLLI", "XXJ_ZZLLLI", "XXX__ZZXLI", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "O→S" },
        { grid: ["_SS_______", "SS________", "OOJJ__L__I", "OOJ___LLLI", "XXJTZZLLLI", "XXXTTZZXLI", "XXXTXXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "" },
        { grid: ["_________I", "_________I", "_________I", "LLLJ___OOI", "LXXJ__SOOZ", "XXJJ__SSZZ", "XXXX__XSZX", "XXXTTTXXXX", "XXXXTXXXXX"], percent: null, pieces: "", comment: "5巡パフェルート" },
        { grid: ["_________I", "_________I", "_________I", "LLLJ___OOI", "LXXJ__SOOZ", "XXJJ__SSZZ", "XXXX__XSZX"], percent: null, pieces: "", comment: "5巡パフェルート" },
        { grid: ["________OO", "I_______OO", "IJJZ___LLX", "IJZZ____LX", "IJZTTTSSLX", "XXXXTSSXXX", "XXXX__XXXX", "XXXX__XXXX", "XXXX__XXXX"], percent: null, pieces: "", comment: "5巡パフェルート" },
        { grid: ["________OO", "I_______OO", "IJJZ___LLX", "IJZZ____LX", "XXXX__XXXX", "XXXX__XXXX", "XXXX__XXXX"], percent: null, pieces: "", comment: "5巡パフェルート" },
      ],
    },
    {
      id: "meisou", title: "迷走砲", source: "https://w.atwiki.jp/tetrismaps/pages/478.html", total: 9,
      forms: [
        { grid: ["_________I", "__L__T_ZJI", "OOL_TTZZJI", "OOLL_TZJJI"], percent: null, pieces: "", comment: "迷走砲" },
        { grid: ["ILOO______", "ILOO__S__Z", "ILL___SSZZ", "ISS_JJJSZX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "LO" },
        { grid: ["OO________", "OO________", "IIII__S__Z", "LLL___SSZZ", "LSS_JJJSZX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "LIO" },
        { grid: ["_______S__", "_______SS_", "ILLL__OOS_", "ILZ___OOSS", "IZZ_JJJSSX", "IZX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "ZL" },
        { grid: ["LL________", "IL_____Z__", "ILSS__ZZ__", "ISS___ZOO_", "ISS_JJJOOX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "IL+OZ" },
        { grid: ["ILLL___Z__", "ILSS__ZZ__", "ISS___ZOO_", "ISS_JJJOOX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "SL+OZ" },
        { grid: ["_______OO_", "IIII__SOOZ", "LLL___SSZZ", "LSS_JJJSZX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "LI(右のSZOは循環)" },
        { grid: ["I_________", "IZZ_______", "ISZZ__SLL_", "ISS___SSL_", "OOS_JJJSLX", "OOX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "OI+OSZ" },
        { grid: ["__Z_______", "IZZ_______", "IZSS__LLL_", "ISS___LOO_", "ISS_JJJOOX", "SSX__XJXXX", "XXX_XXXXXX", "XXXX_XXXXX"], percent: null, pieces: "", comment: "SZ+OL" },
      ],
    },
  ] };
})();
